name: stay-awake-odin

env:
    package_name: stay-awake-odin
    exe_name: stay-awake

on:
  push:
    tags:
      - '*'

jobs:
    build-win:
        runs-on: windows-latest
        env:
          target: x86_64-pc-windows-msvc
        steps:
            - name: Get git tag version
              id: get_version
              run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
              shell: bash
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install toolchain
              uses: laytan/setup-odin@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }} 
            - name: Build
              run: .\build.bat
            - name: Zip
              run: Compress-Archive -Path ${{ env.EXE_NAME }}.exe -DestinationPath ${{ env.PACKAGE_NAME }}-${{ steps.get_version.outputs.VERSION }}-${{ env.TARGET }}.zip  -CompressionLevel Optimal
              shell: powershell
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  ${{ env.PACKAGE_NAME }}-${{ steps.get_version.outputs.VERSION }}-${{ env.TARGET }}.zip
                token:
                  ${{ secrets.GITHUB_TOKEN }}